#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.3.0f1_ffacea4b84e7"
#define UNITY_VERSION_FULL_NICE "2019.3.0f1 (ffacea4b84e7)"
#define UNITY_VERSION_BLD 16755946
#define UNITY_VERSION_DATE 1574394952
#define UNITY_VERSION_WIN "2019.3.0.16755946"
#define UNITY_VERSION_BRANCH "2019.3/staging"
